package(
    default_visibility = ["//visibility:public"]
)

cc_binary(
    name="vrm",
    srcs=[
        "src/vrm.cpp",
        "src/Lexer.cpp",
        "src/Lexer.h",
        "src/Parser.cpp",
        "src/Parser.h",
        "src/SymbolTable.cpp",
        "src/SymbolTable.h",
        "src/AstPrinter.cpp",
        "src/AstPrinter.h",
        "src/CPrinter.cpp",
        "src/CPrinter.h",
        "src/StringBuffer.cpp",
        "src/StringBuffer.h",
        "src/Array.h",
        "src/mytypes.h",
        "src/FileData.h",
        "src/FileData.cpp",
        "src/PoolAllocator.h",
        "src/PoolAllocator.cpp",
        "src/TextType.h",
        "src/TextType.cpp",
        "src/Token.h",
        "src/Token.cpp",
        "src/TokenType.h",
        "src/SrcLocation.h",
        "src/ast.h",
    ],
)

cc_library(
    name="vrm_headers",
    hdrs=[
        "include/vrm_preamble.h",
        "include/circular_buffer.h",
    ],
    includes=[
        "include",
    ]
)