[build-system]
requires = [
    "setuptools>=42",
    "scikit-build>=0.13",
    "cmake>=3.18",
    "ninja",
]
build-backend = "setuptools.build_meta"

[project]
name = "pycbuf"
readme = "README.md"
dynamic = ["authors", "license", "version", "description"]
requires-python = ">=3.10"
