
macro( fetch_dependency target url tag  )
  include(FetchContent)
  if (NOT TARGET ${target})
    find_file(${target}_project ${target}.project PATHS ../${target} ../../${target} ../../../${target} )
    if (NOT ${target}_project)
        FetchContent_Declare( ${target} GIT_REPOSITORY ${url} )
        FetchContent_GetProperties( ${target} )
        if( NOT ${target}_POPULATED )
        execute_process(COMMAND ${CMAKE_COMMAND} -E echo_append "-- Downloading ${target} ")
        FetchContent_Populate( ${target} )
        message( "into ${${target}_SOURCE_DIR}... done." )
        add_subdirectory( ${${target}_SOURCE_DIR}  ${${target}_BINARY_DIR} )
        endif()
    else()
        get_filename_component( dir ${${target}_project} DIRECTORY )
        set(${target}_SOURCE_DIR ${dir})
        message( "-- Using ${target} on the local disk at: ${${target}_SOURCE_DIR}" )
        add_subdirectory( ${${target}_SOURCE_DIR} ${CMAKE_CURRENT_BINARY_DIR}/${target} )
    endif()
  endif()
endmacro()
