name: CI

on:
  push:
    branches: [main]
    tags: ["releases/**"]
  pull_request:
    branches: ["*"]

jobs:
  cpp-linux:
    runs-on: ubuntu-latest
    steps:
      # Install CMake
      - name: Install CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake
      # Clone the repository
      - uses: actions/checkout@v4
      # CMake configure and build
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          make
      # Run tests
      - name: Test
        run: |
          cd build
          ctest --output-on-failure

  # TODO(https://github.com/Verdant-Robotics/cbuf/issues/4): Fix Windows build
  # cpp-windows:
  #   runs-on: windows-latest
  #   steps:
  #     # Install CMake
  #     - name: Install CMake
  #       run: |
  #         choco install cmake
  #     # Clone the repository
  #     - uses: actions/checkout@v4
  #     # CMake configure and build
  #     - name: Build
  #       run: |
  #         mkdir build
  #         cd build
  #         cmake -DCMAKE_BUILD_TYPE=Debug ..
  #         cmake --build . --config Release
  #     # Run tests
  #     - name: Test
  #       run: |
  #         cd build
  #         ctest --output-on-failure

  cpp-macos:
    runs-on: macos-latest
    steps:
      # Install CMake
      - name: Install CMake
        run: |
          brew install cmake
      # Clone the repository
      - uses: actions/checkout@v4
      # CMake configure and build
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          make
      # Run tests
      - name: Test
        run: |
          cd build
          ctest --output-on-failure

  build_wheels:
    name: Build Python wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v3

      - name: Install python3-dev
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.15.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
